language: go

go:
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - rm -rf $GOPATH/src/gopkg.in/src-d
  - mkdir -p $GOPATH/src/gopkg.in/src-d
  - ln -s $PWD $GOPATH/src/gopkg.in/src-d/enry.v1
  - cd $GOPATH/src/gopkg.in/src-d/enry.v1
  - go get -v -t ./...

script:
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN 
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
